# Site settings
title: "Indy Elixir: The Indianapolis Elixir Users Group"
email: hello@indyelixir.org
description: "Join fellow Elixirists in Indianapolis to learn about building real-time apps lightning-fast APIs, and connected devices with Elixir and OTP."
baseurl: ""
url: "http://www.indyelixir.org"
twitter_username: indyelixir
github_username:  indyelixir

# Build settings
markdown: kramdown
permalink: pretty

paginate: 10

gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from _site
exclude:
  - CNAME
  - README.md
  - Gemfile
  - Gemfile.lock

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
